### ISSUE TITLE
Building a blob file

### ISSUE THREAD

**Issue by spasse** [marvell-iot/ez-connect-lite#1]
With previous marvell based projects I had control of flash layout via "layout.txt".
After setting up the flash partitions I could flash any combination of images as needed.
It appears that with the AWS iot ez-connect design I must load either a complete "blob",
or just the app itself.  The documentation tree appears to be in churn, whatever search I
make, I end up @ "Head over to our new documentation" page, which doesn't provide anything useful.

How are blobs built?
How can the flash partition table be modified?
How are "over-the-air" updates handled?

**Comment by anujdeshpande** [comment]
Hey @spasse - Thanks for the feedback ! 

The new landing page http://marvell-iot.github.io/ and the docs page http://marvell-iot.github.io/docs/ will be replacing the wiki. Right now all the content that was present on the wiki pages has been migrated here. 

Support for building blobs, editing flash layout/partition table as well as over the air updates is not yet present in `aws_starter_sdk` or `ez-connect-lite`.
I am in the process of adding support for flashing multiple components, and you can expect a new release here soon (in a week or less). 

As a side note :  
The `aws_starter_sdk` that was made available on GitHub was meant to provide an easy way of connecting to the AWS IoT cloud using the [AWS Starter Kit](https://www.amazon.com/Globalscale-MW302-IoT-Starter-Powered/dp/B0168DLQHI/ref=sr_1_1) from Globalscale. It was never meant as a replacement/alternative to the EZ Connect SDK from Marvell, hence the lack of traditionally necessary features. As more boards becomes available ( [here](http://buyiot.net) and [here](https://makerville.io/knit) ), it makes sense to add more features, which may not be AWS IoT centric. With this new repo, `ez-connect-lite`, we'll be doing just.

**Comment by anujdeshpande** [comment]
I have merged some changes in the master that now let you edit the layout, flash individual components, etc. Blob building and OTA updates are not yet supported in EZ Connect Lite.

**Comment by zhangjr1970** [comment]
I download the ez-connect-lite , using federo25 and AWS  starter IOT develope board mw30x .
I run the make. in ez-connect dir. and get error. as.

make[1]: Entering directory '/opt/marvell/ez-connect-lite'
 [axf] /opt/marvell/ez-connect-lite/bin/mw302_rd/aws_starter_demo.axf
sdk/libs/libwmsdk.a(internal_fp0.o): In function `MatchDomainName.part.3':
(.text.MatchDomainName.part.3+0xa0): undefined reference to `__ctype_ptr__'
sdk/libs/libwmsdk.a(integer_fp0.o): In function `mp_read_radix':
(.text.mp_read_radix+0x98): undefined reference to `__ctype_ptr__'
sdk/libs/libwmsdk.a(asn_fp0.o): In function `MatchBaseName':
(.text.MatchBaseName+0xb8): undefined reference to `__ctype_ptr__'
sdk/libs/libwmsdk.a(hexbin.o): In function `hex2bin':
(.text.hex2bin+0x90): undefined reference to `__ctype_ptr__'
sdk/libs/libwmsdk.a(strntoumax.o): In function `strntoumax':
(.text.strntoumax+0x10c): undefined reference to `__ctype_ptr__'
sdk/libs/libwmsdk.a(strncasecmp.o):(.text.strncasecmp+0x48): more undefined references to `__ctype_ptr__' follow
collect2: error: ld returned 1 exit status
build/rules.mk:288: recipe for target 'bin/mw302_rd/aws_starter_demo.axf' failed
make[1]: *** [bin/mw302_rd/aws_starter_demo.axf] Error 1
make[1]: Leaving directory '/opt/marvell/ez-connect-lite'
Makefile:30: recipe for target 'do_the_build' failed
make: *** [do_the_build] Error 2

the helloworld app is good.but others is not.

can I get some help!  Thank you.

**Comment by ssyuan1234** [comment]
I got similar error messages as zhangjr1970. Do you have solution on that?

Thanks!

**Comment by herbertjkelly** [comment]
Seeing the same issue trying to build the aws_starter_sdk ...

/ez-connect-lite/bin/mw302_rd/aws_starter_demo.axf
sdk/libs/libwmsdk.a(internal_fp0.o): In function `MatchDomainName.part.3':
(.text.MatchDomainName.part.3+0xa0): undefined reference to `__ctype_ptr__'
sdk/libs/libwmsdk.a(integer_fp0.o): In function `mp_read_radix':
(.text.mp_read_radix+0x98): undefined reference to `__ctype_ptr__'
sdk/libs/libwmsdk.a(asn_fp0.o): In function `MatchBaseName':
(.text.MatchBaseName+0xb8): undefined reference to `__ctype_ptr__'
sdk/libs/libwmsdk.a(hexbin.o): In function `hex2bin':
(.text.hex2bin+0x90): undefined reference to `__ctype_ptr__'
sdk/libs/libwmsdk.a(strntoumax.o): In function `strntoumax':
(.text.strntoumax+0x10c): undefined reference to `__ctype_ptr__'
sdk/libs/libwmsdk.a(strncasecmp.o):(.text.strncasecmp+0x48): more undefined references to `__ctype_ptr__' follow
collect2: error: ld returned 1 exit status

Is this some library that changed ? would appreciate your input.
